FROM oven/bun:1

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/http-server ./apps/http-server

RUN bun install
RUN cat ~/.env
RUN bun run db:generate

EXPOSE 8081

CMD ["bun","run","start:http" ]
